version: '3.8'

services:
  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: "rabbit"
    ports:
      - '5672:5672'
      - '15672:15672'
    expose:
      - "5672"
      - "15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
      - ./docker/conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./docker/conf/definitions.json:/etc/rabbitmq/definitions.json:ro
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    expose:
      - "1025"
      - "8025"
    environment:
      MH_AUTH_FILE: /home/mailhog/mailhog-auth
    volumes:
      - ./envs/mailhog-auth:/home/mailhog/mailhog-auth:ro
  email_notification:
    container_name: email_notification
    image: email_notification:v1.0
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - envs/.email_2.env
    volumes:
      - scr_data:/usr/src/code
    command: ["python", "-c", "while True: pass"]
    depends_on:
      - rabbit
      - mailhog


volumes:
  rabbitmq_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './rabbit_data' 
  scr_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './' 
